### ISSUE TITLE
Classification is Working but not the auto tagging

### ISSUE THREAD

**Issue by Rehvaro** [minutogit/PrioMailbox#3]
Hello

I have train 5 tags, and when I click "Email info" on a unclassified email I have "Probability 100%" in the correct tag, and less than 5% for others.
But when I use "classify email' on this email, it doesn't tag this email with the one that have 100%. In fact in all my tries, the add-on never placed a tag on a email, nor change his color, when I receive of train an untagged email. The "Apply/Remove Tag When Training" is checked.

My threshold is still at the default 99% value.

I have the latest version of Thunderbird (128.4.3) and PrioMailbox (1.0.2)

What could I do to understand what is happening ? 

This add-on would be so useful for me :)

Best regards
Fabien B

**Comment by Rehvaro** [comment]
If it help, in the Thunderbirds console, when I click "Classify", I get :
![image](https://github.com/user-attachments/assets/3ab90f25-41f0-4326-a7bf-d147d390e1f8)

**Comment by minutogit** [comment]
Than you for your report.

It should now work with version 1.0.3. Download it here from GitHub and install it manually. It will take a few more days before it's available on the Thunderbird Add-ons site.

**Comment by Rehvaro** [comment]
Works well !
Thank you very much !

**Comment by prg318** [comment]
Hello!  I'm actually experiencing a very similar error to this with priomailbox 1.4.3.  No tags get applied when pressing classify and the console shows this error:

```
Error retrieving tags for message 5018: TypeError: messenger.messages.update is not a function
    classifyEmail moz-extension://889a3574-2ad5-47ca-9586-db9d6e5b6035/background.js:803
    promise callback*classifyEmail/< moz-extension://889a3574-2ad5-47ca-9586-db9d6e5b6035/background.js:793
    promise callback*classifyEmail moz-extension://889a3574-2ad5-47ca-9586-db9d6e5b6035/background.js:770
    handleMenuClick moz-extension://889a3574-2ad5-47ca-9586-db9d6e5b6035/background.js:405
    handleMenuClick moz-extension://889a3574-2ad5-47ca-9586-db9d6e5b6035/background.js:415
    promise callback*handleMenuClick moz-extension://889a3574-2ad5-47ca-9586-db9d6e5b6035/background.js:375
    <anonymous> moz-extension://889a3574-2ad5-47ca-9586-db9d6e5b6035/background.js:356
    promise callback* moz-extension://889a3574-2ad5-47ca-9586-db9d6e5b6035/background.js:355
```

**Comment by minutogit** [comment]
@prg318 Fixed in v1.4.4 ! Thank you very much for this report!
